version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=caltia_admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=caltia_caltia
  app:
     image: node:11
     ports:
       - "3004:3004"
     working_dir: /usr/src/caltia/
     restart: always
     volumes:
       - .:/usr/src/caltia
     command: bash -c "npm install && npm i -g sequelize-cli && sequelize db:migrate && npm i -g bower && bower install --force-latest --allow-root && npm start"
     environment:
       - CAL_DB_USERNAME=caltia_admin
       - CAL_DB_PASSWORD=12345
       - CAL_DB_NAME=caltia_caltia
       - CAL_DB_PORT=5432
       - CAL_DB_HOST=db
       - APP_ADMIN_EMAIL=admin@admin.com
       - APP_ADMIN_PASS=12345
       - APP_URL=http://198.101.187.112:3004
       - APP_PORT=3004
